import { ProjectProps } from './Project';

export const ProjectList: ProjectProps[] = [
  {
    prefix: 'Work:',
    title: 'Developed and mantained the FedEx rating application',
    // description: 'description',
    image: 'projects/fedex.png',
    skills: ['typescript', 'angular', 'ngrx', 'jasmine', 'karma', 'optimizely'],
    demo: 'https://www.fedex.com/en-nl/online/rating.html',
    date: 'Jan 2021 - Present',
  },
  {
    prefix: 'Work:',
    title: 'Developed a web application for InfrontFinance (ex VWD)',
    // description: 'description',
    image: 'projects/vwd-group.png',
    skills: ['typescript', 'angular', 'ngrx', 'jasmine', 'karma', 'bootstrap'],
    date: 'Jan 2020 - Dec 2020',
    customClass: 'bg-center',
    website: 'https://www.infrontfinance.com/',
  },
  {
    prefix: 'Work:',
    title: 'Provided services as freelancer in Fiverr',
    // description: 'description',
    image: 'projects/fiverr.jpg',
    skills: ['selenium', 'python', 'telegram', 'nodejs', 'sqlite'],
    website: 'https://www.fiverr.com/helias32',
    date: 'Aug 2018 - Jan 2020',
    customClass: 'bg-center',
  },
  {
    prefix: 'Work:',
    title: 'Software Management for NewTecna & ItaliaHotspot',
    // description: 'description',
    image: 'projects/newtecna.jpg',
    skills: ['typescript', 'angular', 'php', 'laravel', 'bootstrap', 'mysql'],
    date: 'Mar 2018 - Oct 2019',
    website: 'https://lnx.newtecna.com/',
  },
  {
    prefix: 'Work:',
    title: 'Software management developed for Codice a Barre Italia & GirasoleEventi',
    // description: 'description',
    image: 'projects/CodiceaBarreSM.jpg',
    skills: ['angular', 'typescript', 'php', 'laravel', 'bootstrap', 'mysql'],
    demo: 'https://www.youtube.com/watch?v=rXr_9CRw8lk',
    date: 'Sep 2017 - Jan 2018',
    customClass: 'bg-center',
    website: 'https://codiceabarra.it/',
  },
  {
    prefix: 'Work:',
    title: 'Software management developed for PerdichizziGioiellerie',
    // description: 'description',
    image: 'projects/perdichizzi.png',
    skills: ['angular', 'typescript', 'php', 'laravel', 'bootstrap', 'mysql'],
    date: 'Oct 2016 - Jul 2017',
    customClass: 'bg-center',
    website: 'https://www.gioielleriaperdichizzi.it/',
  },
  {
    prefix: 'Work:',
    title: 'BarcodeDatabase, website for Codice a Barre Italia',
    // description: 'description',
    image: 'projects/BarcodeDatabase.png',
    skills: ['php', 'javascript', 'jquery', 'mysql', 'bootstrap'],
    demo: 'http://161.97.105.183:8080/BarcodeDatabase/index.php',
    date: 'Aug 2016 - Oct 2016',
  },
  {
    prefix: 'Work:',
    title:
      'Consultant for ItaliaHotspot, developing a web interface, RadiusServer interface and OpenWRT OS',
    // description: 'description',
    image: 'projects/italiahotspot.png',
    skills: ['angular', 'php', 'typescript', 'mysql', 'bootstrap'],
    website: 'https://italiahotspot.it/landing/index.html',
    date: 'Aug 2015 - Jul 2016',
  },
  {
    prefix: 'Work:',
    title: 'Consultant for Insolaria, developing a web application',
    // description: 'description',
    image: 'projects/insolaria.png',
    skills: ['angular', 'php', 'typescript', 'mysql', 'bootstrap', 'laravel', 'oauth'],
    date: 'Jan 2015 - Jul 2015',
  },
];
