import { ProjectProps } from './Project';

export const ProjectList: ProjectProps[] = [
  {
    prefix: '👔 Work:',
    title: 'Developed and mantained the FedEx rating application',
    // description: 'description',
    image: 'projects/fedex.png',
    skills: [
      'typescript',
      'angular',
      'ngrx',
      'jasmine',
      'karma',
      'optimizely',
      'nx',
      'rxjs',
      'cypressio',
      'githubactions',
      'jenkins',
      'docker',
    ],
    demo: 'https://www.fedex.com/en-nl/online/rating.html',
    date: 'Jan 2021 - Present',
  },
  {
    prefix: '👔 Work:',
    title: 'Developed a web application for InfrontFinance (ex VWD)',
    // description: 'description',
    image: 'projects/vwd-group.png',
    skills: ['typescript', 'angular', 'ngrx', 'jasmine', 'karma', 'bootstrap', 'rxjs'],
    date: 'Jan 2020 - Dec 2020',
    customClass: 'no-bg-cover bg-[length:100%] bg-no-repeat bg-center',
    website: 'https://www.infrontfinance.com/',
  },
  {
    prefix: '👔 Work:',
    title: 'Provided services as freelancer in Fiverr',
    // description: 'description',
    image: 'projects/fiverr.jpg',
    skills: ['selenium', 'python', 'telegram', 'nodejs', 'sqlite'],
    website: 'https://www.fiverr.com/helias32',
    date: 'Aug 2018 - Jan 2020',
    customClass: 'bg-center',
  },
  {
    prefix: '👔 Work:',
    title: 'Software Management for NewTecna & ItaliaHotspot',
    // description: 'description',
    image: 'projects/newtecna.jpg',
    skills: ['typescript', 'angular', 'php', 'laravel', 'bootstrap', 'mysql', 'rxjs'],
    date: 'Mar 2018 - Oct 2019',
    website: 'https://lnx.newtecna.com/',
  },
  {
    prefix: '👔 Work:',
    title: 'Software management developed for Codice a Barre Italia & GirasoleEventi',
    // description: 'description',
    image: 'projects/CodiceaBarreSM.jpg',
    skills: ['angular', 'typescript', 'php', 'laravel', 'bootstrap', 'mysql', 'rxjs'],
    demo: 'https://www.youtube.com/watch?v=rXr_9CRw8lk',
    date: 'Sep 2017 - Jan 2018',
    customClass: 'bg-center',
    website: 'https://codiceabarra.it/',
  },
  {
    prefix: '👔 Work:',
    title: 'Software management developed for PerdichizziGioiellerie',
    // description: 'description',
    image: 'projects/perdichizzi.png',
    skills: ['angular', 'typescript', 'php', 'laravel', 'bootstrap', 'mysql', 'rxjs'],
    date: 'Oct 2016 - Jul 2017',
    customClass: 'no-bg-cover bg-[length:100%] bg-no-repeat bg-center',
    website: 'https://www.gioielleriaperdichizzi.it/',
  },
  {
    prefix: '👔 Work:',
    title: 'BarcodeDatabase, website for Codice a Barre Italia',
    // description: 'description',
    image: 'projects/BarcodeDatabase.png',
    skills: ['php', 'javascript', 'jquery', 'mysql', 'bootstrap'],
    demo: 'http://161.97.105.183:8080/BarcodeDatabase/index.php',
    date: 'Aug 2016 - Oct 2016',
  },
  {
    prefix: '👔 Work:',
    title:
      'Consultant for ItaliaHotspot, developing a web interface, RadiusServer interface and OpenWRT OS',
    // description: 'description',
    image: 'projects/italiahotspot.png',
    skills: ['angular', 'php', 'typescript', 'mysql', 'bootstrap', 'rxjs'],
    website: 'https://italiahotspot.it/landing/index.html',
    date: 'Aug 2015 - Jul 2016',
    customClass: 'bg-center',
  },
  {
    prefix: '👔 Work:',
    title: 'Consultant for Insolaria, developing a web application',
    // description: 'description',
    image: 'projects/insolaria.png',
    skills: ['angular', 'php', 'typescript', 'mysql', 'bootstrap', 'laravel', 'oauth', 'rxjs'],
    date: 'Jan 2015 - Jul 2015',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'Keira3 web application',
    // description: 'description',
    image: 'projects/Keira3.png',
    skills: [
      'angular',
      'typescript',
      'mysql',
      'electron',
      'nx',
      'nodejs',
      'sqlite',
      'rxjs',
      'playwright',
      'githubactions',
    ],
    github: 'https://github.com/azerothcore/Keira3',
    website: 'https://azerothcore.org/Keira3',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'AzerothCore, complete open source and modular solution for MMO',
    // description: 'description',
    image: 'projects/azerothcore.png',
    skills: ['cplusplus', 'c', 'lua', 'mysql', 'bash', 'githubactions', 'docker'],
    github: 'https://github.com/azerothcore/azerothcore-wotlk',
    website: 'https://azerothcore.org/',
    customClass: 'no-bg-cover bg-[length:100%] bg-no-repeat bg-center',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'Git-catalogue, a web application to catalog git repositories',
    // description: 'description',
    image: 'projects/git-catalogue.png',
    skills: ['angular', 'typescript', 'rxjs', 'githubactions'],
    github: 'https://github.com/azerothcore/git-catalogue',
    demo: [
      'https://azerothcore.org/catalogue',
      'https://unict-dmi.github.io/git-catalogue/',
      'https://unict-quality-development.github.io/git-catalogue/#/tab/unict-qd',
    ],
    customClass: 'no-bg-cover bg-[length:100%] bg-no-repeat bg-center',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'Server-status, web application',
    // description: 'description',
    image: 'projects/server-status.png',
    skills: ['angular', 'typescript', 'rxjs'],
    github: 'https://github.com/azerothcore/server-status',
    demo: 'http://chromiecraft.com/apps/server-status',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'Arena-stats, web application',
    // description: 'description',
    image: 'projects/arena-stats.png',
    skills: ['angular', 'typescript', 'rxjs'],
    github: 'https://github.com/azerothcore/arena-stats',
    demo: 'http://chromiecraft.com/apps/arena-stats',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'Acore API, RESTful APIs for Azerothcore written in NestJS',
    // description: 'description',
    image: 'projects/acore-api.png',
    skills: ['typescript', 'nodejs', 'nestjs', 'docker'],
    github: 'https://github.com/azerothcore/acore-api',
    customClass: 'no-bg-cover bg-[length:100%] bg-no-repeat bg-center',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'Telegram automated db backup',
    // description: 'description',
    image: 'https://github.com/azerothcore/telegram-automated-db-backup/raw/master/icon.png',
    skills: ['telegram', 'python', 'bash', 'mysql'],
    github: 'https://github.com/azerothcore/telegram-automated-db-backup',
    customClass: 'no-bg-cover bg-[length:80%] bg-no-repeat bg-center',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'Telegram DMI Bot',
    // description: 'description',
    image: 'https://github.com/UNICT-DMI/Telegram-DMI-Bot/raw/master/icon.png',
    skills: ['telegram', 'python', 'pytest', 'docker', 'sqlite', 'fastapi'],
    github: 'https://github.com/UNICT-DMI/Telegram-DMI-Bot',
    demo: 'https://t.me/DMI_Bot',
    customClass: 'no-bg-cover bg-[length:80%] bg-no-repeat bg-center',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'ERSU Bot',
    // description: 'description',
    image: 'https://github.com/UNICT-DMI/ERSU-Bot/raw/main/icon.png',
    skills: ['telegram', 'python', 'pytest', 'docker', 'sqlite'],
    github: 'https://github.com/UNICT-DMI/ERSU-Bot',
    demo: ['https://t.me/ERSU_Bot', 'https://t.me/ersunews'],
    website: 'https://www.ersucatania.it/piattaforma-telegram-per-gli-studenti/',
    customClass: 'no-bg-cover bg-[length:80%] bg-no-repeat bg-center',
  },
  {
    prefix: '🤝 Opensource:',
    title: 'Spotted DMI Bot',
    // description: 'description',
    image: 'https://github.com/UNICT-DMI/Telegram-SpottedDMI-Bot/raw/main/icon.png',
    skills: ['telegram', 'python', 'pytest', 'docker', 'sqlite'],
    github: 'https://github.com/UNICT-DMI/Telegram-SpottedDMI-Bot',
    demo: ['https://t.me/Spotted_DMI_Bot', 'https://t.me/Spotted_DMI'],
    customClass: 'no-bg-cover bg-[length:80%] bg-no-repeat bg-center',
  },

  {
    prefix: '🤝 Opensource:',
    title: 'UNICT Telegram Hub',
    // description: 'description',
    image: 'projects/unict-telegram-hub.png',
    skills: ['telegram', 'typescript', 'react', 'nextjs', 'docker'],
    github: 'https://github.com/UNICT-DMI/unict-telegram-hub',
    demo: 'https://telegram.unictdev.org/',
  },
];

export const allSkills = new Set([...ProjectList.map((p) => p.skills)].flat());
