// Display names for the devicon ids used in ProjectList; unlisted ids fall back to the id itself.
export const SKILL_LABELS: Record<string, string> = {
  android: 'Android',
  angular: 'Angular',
  azure: 'Azure',
  bash: 'Bash',
  bootstrap: 'Bootstrap',
  c: 'C',
  cplusplus: 'C++',
  csharp: 'C#',
  cypressio: 'Cypress',
  docker: 'Docker',
  dotnetcore: '.NET',
  electron: 'Electron',
  express: 'Express.js',
  fastapi: 'FastAPI',
  githubactions: 'GitHub Actions',
  jasmine: 'Jasmine',
  java: 'Java',
  javascript: 'JavaScript',
  jenkins: 'Jenkins',
  jquery: 'jQuery',
  karma: 'Karma',
  laravel: 'Laravel',
  lua: 'Lua',
  matplotlib: 'Matplotlib',
  mongodb: 'MongoDB',
  mysql: 'MySQL',
  nestjs: 'NestJS',
  nextjs: 'Next.js',
  ngrx: 'NgRx',
  nodejs: 'Node.js',
  nx: 'Nx',
  oauth: 'OAuth',
  optimizely: 'Optimizely',
  php: 'PHP',
  playwright: 'Playwright',
  plotly: 'Plotly',
  powershell: 'PowerShell',
  processing: 'Processing',
  pytest: 'Pytest',
  python: 'Python',
  pytorch: 'PyTorch',
  r: 'R',
  react: 'React',
  rxjs: 'RxJS',
  scikitlearn: 'scikit-learn',
  selenium: 'Selenium',
  socketio: 'Socket.IO',
  sqlite: 'SQLite',
  tailwindcss: 'Tailwind CSS',
  telegram: 'Telegram Bots',
  threejs: 'Three.js',
  typescript: 'TypeScript',
};
